[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smerfs"
version = "0.1.2"
description = "Stochastic Markov Evaluation of Random Fields on the Sphere (SMERFS)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy", "scipy>=1.15"]
authors=[{name = "Peter Creasey", email="p.e.creasey.00@gmail.com"}]
license = 'MIT'

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Homepage = "https://github.com/pec27/smerfs"
Documentation = "https://github.com/pec27/smerfs#readme"
Repository = "https://github.com/pec27/smerfs.git"